<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bingchunmoli</groupId>
        <artifactId>moli-quick-spring-boot-starter</artifactId>
        <version>1.0.13-bate</version>
    </parent>

    <artifactId>moli-quick-object-storage</artifactId>
    <packaging>pom</packaging>
    <name>moli-quick-object-storage</name>
    <description>Pluggable object storage integrations</description>

    <modules>
        <module>moli-quick-object-storage-core</module>
        <module>moli-quick-object-storage-spring-boot-autoconfigure</module>
        <module>moli-quick-object-storage-oss</module>
        <module>moli-quick-object-storage-obs</module>
        <module>moli-quick-object-storage-cos</module>
        <module>moli-quick-object-storage-s3</module>
    </modules>
</project>
