<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bingchunmoli</groupId>
        <artifactId>moli-quick-object-storage</artifactId>
        <version>1.0.13-bate</version>
    </parent>

    <artifactId>moli-quick-object-storage-cos</artifactId>
    <name>moli-quick-object-storage-cos</name>
    <description>Tencent Cloud COS object storage provider</description>

    <dependencies>
        <dependency>
            <groupId>com.bingchunmoli</groupId>
            <artifactId>moli-quick-object-storage-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.bingchunmoli</groupId>
            <artifactId>moli-quick-object-storage-spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
            <version>5.6.227</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
